/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasPesquisa;

import ClassesEntidades.Marca;
import ClassesEntidades.Modelo;
import ClassesEntidades.Veiculo;
import TelasCruds.CrudVeiculo;
import ValgaSis.Banco;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jucabnu
 */
public class PesquisaVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form pesquisaVeiculo
     */
    public PesquisaVeiculo() {
        initComponents();
        jComboBoxFiltro.removeAllItems();
        jComboBoxFiltro.addItem("Placa");
        jComboBoxFiltro.addItem("Cor");
        jComboBoxFiltro.addItem("Ano");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVeiculos = new javax.swing.JTable();
        jButtonMostrar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonSelecionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxFiltro = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Veículos");

        pesquisa.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        pesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesquisaFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setText("Valor:");

        jTableVeiculos.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTableVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Renavan", "Placa", "Cor", "Ano", "Modelo", "Marca", "Valor R$", "Obs.", "DataIn", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVeiculos);

        jButtonMostrar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Filter.gif"))); // NOI18N
        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Door.gif"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonSelecionar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.gif"))); // NOI18N
        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setText("Filtrar por:");

        jComboBoxFiltro.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(jButtonSelecionar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrar)
                    .addComponent(jButtonSelecionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        atualizaTabelaVeiculos();
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed
    javax.swing.JFrame jframe;

    public void instancia(javax.swing.JFrame jframe) {
        this.jframe = jframe;
    }

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed

        CrudVeiculo telaVei = (CrudVeiculo) this.jframe;
        telaVei.campoRecebeRenavan(jTableVeiculos.getValueAt(jTableVeiculos.getSelectedRow(), 0));
        this.dispose();

    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void pesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisaFocusLost

        jButtonMostrarActionPerformed(null);

    }//GEN-LAST:event_pesquisaFocusLost

    public void atualizaTabelaVeiculos() {
        ArrayList<Veiculo> listaVeiculo = Banco.selectVeiculoPesquisa(
                pesquisa.getText().toUpperCase(), String.valueOf(jComboBoxFiltro.getSelectedItem()));
        insereTabelaVeiculo(listaVeiculo);
    }

    private void insereTabelaVeiculo(ArrayList<Veiculo> listaVeiculo) {
        DefaultTableModel dtmc = new DefaultTableModel(); // criar o modelo da tabela

        Veiculo veiculo;

        //definir colunas que a tabela vai conter
        dtmc.addColumn("RENAVAN");
        dtmc.addColumn("Placa");
        dtmc.addColumn("Cor");
        dtmc.addColumn("Ano");
        dtmc.addColumn("Modelo");
        dtmc.addColumn("Marca");
        dtmc.addColumn("Valor R$");
        dtmc.addColumn("Obs.");
        dtmc.addColumn("DataIn");
        dtmc.addColumn("Status");

        //preencher tabela com dados
        for (Object c2 : listaVeiculo) {
            veiculo = (Veiculo) c2;

            String[] linha = new String[10]; // criar linha com 4 colunas, conforme tabela

            linha[0] = veiculo.getRenavan();
            linha[1] = veiculo.getPlaca();
            linha[2] = veiculo.getCor();
            linha[3] = Integer.toString(veiculo.getAno());
            Modelo model = Banco.selectModelo(veiculo.getModelo());
            linha[4] = model.getDes_modelo();
            Marca marc = Banco.selectMarca(model.getMarca());
            linha[5] = marc.getDes_marca();
            linha[6] = Double.toString(veiculo.getValIn());
            linha[7] = veiculo.getObs_veic();
            linha[8] = veiculo.getDataIn();
            if (veiculo.isStatus() == true) {
                linha[9] = "Vendido";
            } else {
                linha[9] = "Disp.";
            }
            dtmc.addRow(linha); // adicionando a linha criada

        }
        jTableVeiculos.setModel(dtmc);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaVeiculo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JComboBox jComboBoxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVeiculos;
    private javax.swing.JTextField pesquisa;
    // End of variables declaration//GEN-END:variables
}
