/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TelasCruds;

import ClassesEntidades.Cliente;
import ClassesEntidades.Veiculo;
import ClassesEntidades.Venda;
import TelasPesquisa.PesquisaCliente;
import TelasPesquisa.PesquisaVeiculo;
import ValgaSis.Banco;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author jucabnu
 */
public class CrudVenda extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    public CrudVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botaoProcessar = new javax.swing.JButton();
        campoCpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        campoRenavan = new javax.swing.JTextField();
        botaoPesquiVeiculo = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        botaoPesquisaCliente = new javax.swing.JButton();
        jLabelRenavan = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Efetuar Venda");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setText("Cód. Cliente (CPF):");

        botaoProcessar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoProcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.gif"))); // NOI18N
        botaoProcessar.setText("Gravar");
        botaoProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProcessarActionPerformed(evt);
            }
        });

        campoCpf.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCpfFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setText("Cód. Veículo (RENAVAN):");

        jButton11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Door.gif"))); // NOI18N
        jButton11.setText("Sair");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        campoRenavan.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoRenavan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRenavanFocusLost(evt);
            }
        });

        botaoPesquiVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        botaoPesquiVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquiVeiculoActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Abort.gif"))); // NOI18N
        jButtonLimpar.setText("Cancelar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setText("Valor de saída: R$");

        campoValor.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        botaoPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        botaoPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaClienteActionPerformed(evt);
            }
        });

        jLabelRenavan.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelRenavan.setText("*");

        jLabelCpf.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelCpf.setText("*");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setText("Placa:");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setText("Nome:");

        campoVenda.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoVenda.setEnabled(false);
        campoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoVendaFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setText("Número da venda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoRenavan, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jLabelRenavan)
                            .addComponent(jLabelCpf)
                            .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPesquiVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(botaoProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRenavan)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(botaoPesquiVeiculo)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPesquisaCliente))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar)
                    .addComponent(botaoProcessar))
                .addGap(3, 3, 3)
                .addComponent(jButton11)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //  **************************************************
    //  ********************* GRAVAR *********************
    //  **************************************************
    private void botaoProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProcessarActionPerformed

        // INSERT / GRAVAR / PROCESSAR

        Venda v1 = new Venda();
        
        try {
            if (campoVenda.getText().equals("")) {
            } else {
                v1 = Banco.selectVenda(Integer.parseInt(campoVenda.getText()));
            }

            
            // 
            if (v1.getCliente().equals("")) {
                Venda v = new Venda();
                v.setCliente(campoCpf.getText());
                v.setRenavan(campoRenavan.getText());
                v.setValOut(Double.parseDouble(campoValor.getText()));
                
                Veiculo veic = Banco.selectVeiculo(campoRenavan.getText());
                if(veic.isStatus() == false){
                    Banco.insertVenda(v);
                    JOptionPane.showMessageDialog(null, "A venda foi registrada com sucesso!");}
                else{                    
                    JOptionPane.showMessageDialog(null, "O RENAVAN informado aponta para veículo que já foi vendido.");                    
                }
                
            } else {
            }
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage() + ")");
            jButtonLimparActionPerformed(null);
        }
    }//GEN-LAST:event_botaoProcessarActionPerformed

    //  **************************************************
    //  ********************* MOSTRAR *********************
    //  **************************************************
    private void campoCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCpfFocusLost

        try {
            if (campoCpf.getText().equals("")) {
            } else {
                Cliente clie = Banco.selectCliente(campoCpf.getText());
                jLabelCpf.setText(clie.getNome());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage() + ")");
            jButtonLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoCpfFocusLost

    //  **************************************************
    //  ******************** MOSTRAR *********************
    //  **************************************************
    private void campoRenavanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRenavanFocusLost

        try {
            if (campoRenavan.getText().equals("")) {
            } else {
                Veiculo veic = Banco.selectVeiculo(campoRenavan.getText());
                jLabelRenavan.setText(veic.getPlaca());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage() + ")");
            jButtonLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoRenavanFocusLost

    //  **************************************************
    //  ********************* FECHAR *********************
    //  ************************************************** 
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    //  **************************************************
    //  *************** LIMPAR / CANCELAR ****************
    //  **************************************************
    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed

        campoCpf.setText("");
        campoRenavan.setText("");
        campoValor.setText("");
        jLabelCpf.setText("");
        jLabelRenavan.setText("");
        campoVenda.setText("");

    }//GEN-LAST:event_jButtonLimparActionPerformed

    //  **************************************************
    //  ******************** PESQUISA *********************
    //  **************************************************
    private void botaoPesquiVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquiVeiculoActionPerformed

        PesquisaVeiculo telaVei = new PesquisaVeiculo();
        telaVei.instancia(this);
        telaVei.setVisible(true);
        
    }//GEN-LAST:event_botaoPesquiVeiculoActionPerformed

    //  **************************************************
    //  ******************** MOSTRAR *********************
    //  **************************************************
    private void campoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoVendaFocusLost

        try {
            if (campoVenda.getText().equals("")) {
            } else {
                Venda v = Banco.selectVenda(Integer.parseInt(campoVenda.getText()));
                campoCpf.setText(v.getCliente());
                if (campoCpf.getText().equals("")) {
                } else {
                    Cliente clie = Banco.selectCliente(campoCpf.getText());
                    jLabelCpf.setText(clie.getNome());
                }
                campoRenavan.setText(v.getRenavan());
                if (campoRenavan.getText().equals("")) {
                } else {
                    Veiculo veic = Banco.selectVeiculo(campoRenavan.getText());
                    jLabelRenavan.setText(veic.getPlaca());
                }
                campoValor.setText(Double.toString(v.getValOut()));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Apenas números inteiros são permitidos para o número da venda!"
                    + "\n"
                    + "\n" + "(Error Exception: " + e.getMessage() + ")");
            jButtonLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoVendaFocusLost

    private void botaoPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaClienteActionPerformed
        
        PesquisaCliente tela = new PesquisaCliente();
        tela.instancia(this);
        tela.setVisible(true);

        
    }//GEN-LAST:event_botaoPesquisaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudVenda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquiVeiculo;
    private javax.swing.JButton botaoPesquisaCliente;
    private javax.swing.JButton botaoProcessar;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoRenavan;
    private javax.swing.JTextField campoValor;
    private javax.swing.JTextField campoVenda;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelRenavan;
    // End of variables declaration//GEN-END:variables
}
