package TelasCruds; 

import ClassesEntidades.Cliente;
import ClassesEntidades.Marca;
import ClassesEntidades.Modelo;
import ClassesEntidades.Veiculo;
import TelasPesquisa.PesquisaCliente;
import TelasPesquisa.PesquisaModelo;
import TelasPesquisa.PesquisaVeiculo;
import ValgaSis.Banco;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author jucabnu
 */
public class CrudVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form crudVeiculo
     */
    public CrudVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        campoRenavan = new javax.swing.JTextField();
        campoPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoCor = new javax.swing.JTextField();
        campoAno = new javax.swing.JTextField();
        botaoLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObs = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botaoGravar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        campoModelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoMarca = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabelModelo = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        campoStatus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Veículo");

        campoRenavan.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoRenavan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRenavanFocusLost(evt);
            }
        });

        campoPlaca.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setText("Cor:");

        campoCor.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        campoAno.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        botaoLimpar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Abort.gif"))); // NOI18N
        botaoLimpar.setText("Cancelar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setText("Ano:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setText("Observações:");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jButton10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton10FocusLost(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Door.gif"))); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        campoObs.setColumns(20);
        campoObs.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoObs.setLineWrap(true);
        campoObs.setRows(5);
        campoObs.setTabSize(0);
        jScrollPane1.setViewportView(campoObs);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setText("Placa:");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setText("Cód. Veículo (RENAVAN):");

        botaoGravar.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.gif"))); // NOI18N
        botaoGravar.setText("Gravar");
        botaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.gif"))); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setText("Valor de entrada: R$");

        campoValor.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setText("Cliente (CPF) entrada:");

        campoCpf.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCpfFocusLost(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setText("Modelo:");

        campoModelo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoModeloFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setText("Marca:");

        campoMarca.setEditable(false);
        campoMarca.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        campoMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoMarcaFocusLost(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabelModelo.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelModelo.setText("*");

        jLabelMarca.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelMarca.setText("*");

        jLabelCpf.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabelCpf.setText("*");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel10.setText("Nome:");

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Find.gif"))); // NOI18N
        jButton18.setEnabled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        campoStatus.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel11.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoStatus)
                            .addComponent(campoCpf)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoCor, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelModelo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMarca))
                                    .addComponent(jLabelCpf)
                                    .addComponent(campoPlaca)
                                    .addComponent(campoAno)
                                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campoRenavan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoRenavan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton18)
                    .addComponent(jLabelMarca))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGravar)
                    .addComponent(botaoExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair)
                    .addComponent(botaoLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void campoRecebeRenavan(Object o) {
        campoRenavan.setText(String.valueOf(o));
    }

    //  **************************************************
    //  *************** LIMPAR / CANCELAR ****************
    //  **************************************************
    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed

        // LIMPAR / CANCELAR

        campoRenavan.setText("");
        campoPlaca.setText("");
        campoCor.setText("");
        campoAno.setText("");
        campoValor.setText("");
        campoCpf.setText("");
        campoObs.setText("");
        campoMarca.setText("");
        campoModelo.setText("");
        jLabelMarca.setText("*");
        jLabelModelo.setText("*");
        jLabelCpf.setText("*");
        campoStatus.setText("");

    }//GEN-LAST:event_botaoLimparActionPerformed

    //  **************************************************
    //  ********************* FECHAR *********************
    //  **************************************************
    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed

        this.dispose();

    }//GEN-LAST:event_botaoSairActionPerformed

    //  **************************************************
    //  ********************* DELETE *********************
    //  **************************************************
    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed

        Banco.deleteRegistro("renavan", "tab_veiculos", campoRenavan.getText());
        botaoLimparActionPerformed(evt);
        JOptionPane.showMessageDialog(null, "Veículo excluído com sucesso!");
    }//GEN-LAST:event_botaoExcluirActionPerformed

    //  **************************************************
    //  **************** GRAVAR / ALTERAR ****************
    //  **************************************************
    private void botaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarActionPerformed

        Veiculo v1 = new Veiculo();

        try {
            if (campoRenavan.getText().equals("")) {
                campoStatus.setText("");
            } else {
                v1 = Banco.selectVeiculo(campoRenavan.getText());
            }

            if (v1.getPlaca().equals("")) {
                // GRAVAR : INSERT
                Veiculo v = new Veiculo();
                v.setRenavan(campoRenavan.getText());
                v.setPlaca(campoPlaca.getText());
                v.setAno(Integer.parseInt(campoAno.getText()));
                v.setCor(campoCor.getText());
                v.setModelo(Integer.parseInt(campoModelo.getText()));
                v.setClienteIn(campoCpf.getText());
                v.setValIn(Double.parseDouble(campoValor.getText()));
                v.setObs_veic(campoObs.getText());
                v.setStatus(false);
                Banco.insertVeiculo(v);
                JOptionPane.showMessageDialog(null, "Veículo cadastrado com sucesso!");
            } else {
                // ALTERAR : UPDATE
                Veiculo v = new Veiculo();
                v.setRenavan(campoRenavan.getText());
                v.setPlaca(campoPlaca.getText());
                v.setAno(Integer.parseInt(campoAno.getText()));
                v.setCor(campoCor.getText());
                v.setModelo(Integer.parseInt(campoModelo.getText()));
                v.setClienteIn(campoCpf.getText());
                v.setValIn(Double.parseDouble(campoValor.getText()));
                v.setObs_veic(campoObs.getText());
                Banco.updateVeiculo(v);
                JOptionPane.showMessageDialog(null, "Alterações gravadas com sucesso!");
            }
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_botaoGravarActionPerformed

    //  **************************************************
    //  ******************** MOSTRAR *********************
    //  **************************************************
    private void campoModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoModeloFocusLost
        // TODO add your handling code here:

        try {
            if (campoModelo.getText().equals("")) {
            } else {
                Modelo model = Banco.selectModelo(Integer.parseInt(campoModelo.getText()));
                jLabelModelo.setText(model.getDes_modelo());
                Marca marc = Banco.selectMarca(model.getMarca());
                campoMarca.setText(Integer.toString(marc.getCod_marca()));
                jLabelMarca.setText(marc.getDes_marca());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Informe apenas números inteiros para o campo código!"
                    + "\n" + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoModeloFocusLost

    private void campoMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMarcaFocusLost

        try {
            if (campoMarca.getText().equals("")) {
            } else {
                Marca marc = Banco.selectMarca(Integer.parseInt(campoMarca.getText()));
                jLabelMarca.setText(marc.getDes_marca());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Informe apenas números inteiros para o campo código!"
                    + "\n" + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoMarcaFocusLost

    private void campoRenavanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRenavanFocusLost

        // MOSTRAR : SELECT

        try {
            if (campoRenavan.getText().equals("")) {
                // nada
                System.out.println("nada1");
            } else {
                Veiculo veic = Banco.selectVeiculo(campoRenavan.getText());
                if (veic.getPlaca().equals("")) {
                    System.out.println("RENAVAN não encontrado...");
                } else {
                    // seleciona modelo, seta o campo e o label
                    Modelo model = Banco.selectModelo(veic.getModelo());
                    campoModelo.setText(Integer.toString(veic.getModelo()));
                    jLabelModelo.setText(model.getDes_modelo());

                    Marca marc = Banco.selectMarca(model.getMarca());
                    campoMarca.setText(Integer.toString(marc.getCod_marca()));
                    jLabelMarca.setText(marc.getDes_marca());

                    Cliente clie = Banco.selectCliente(veic.getClienteIn());
                    campoCpf.setText(veic.getClienteIn());
                    jLabelCpf.setText(clie.getNome());
                }
                campoPlaca.setText(veic.getPlaca());
                campoAno.setText(Integer.toString(veic.getAno()));
                campoCor.setText(veic.getCor());
                campoValor.setText(Double.toString(veic.getValIn()));
                campoObs.setText(veic.getObs_veic());
                if (veic.isStatus() == true) {
                    campoStatus.setText("Vendido!");
                } else {
                    campoStatus.setText("Disponível para venda.");
                }
            }
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoRenavanFocusLost

    private void campoCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCpfFocusLost

        try {
            if (campoCpf.getText().equals("")) {
            } else {
                Cliente c = Banco.selectCliente(campoCpf.getText());
                jLabelCpf.setText(c.getNome());
            }
        } catch (NumberFormatException | HeadlessException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,
                    "Formato inválido informado em algum dos campos ou"
                    + "\n" + "campo obrigatório deixado em branco."
                    + "\n" + "Favor reiniciar o cadastro."
                    + "\n" + "(Error Exception: " + e.getMessage());
            botaoLimparActionPerformed(null);
        }
    }//GEN-LAST:event_campoCpfFocusLost

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        PesquisaVeiculo telaVei = new PesquisaVeiculo();
        telaVei.instancia(this);
        telaVei.setVisible(true);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        PesquisaModelo telaMod = new PesquisaModelo();
        telaMod.setVisible(true);

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        PesquisaCliente telaClie = new PesquisaCliente();
        telaClie.setVisible(true);

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton10FocusLost
        campoRenavanFocusLost(evt);
    }//GEN-LAST:event_jButton10FocusLost

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudVeiculo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoGravar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoCor;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextArea campoObs;
    private javax.swing.JTextField campoPlaca;
    private javax.swing.JTextField campoRenavan;
    private javax.swing.JTextField campoStatus;
    private javax.swing.JTextField campoValor;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
